Resources:
  MyBucketImage:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: lks-kabbanyumas-cana-25
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: GlacierRule
            Prefix: ""
            Status: Enabled
            ExpirationInDays: 365
            Transitions:
              - TransitionInDays: 30
                StorageClass: GLACIER
  MyBucketPolicyImage:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket:
        Ref: 'MyBucketImage'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: "s3:GetObject"
            Resource:
              Fn::Join:
                - ''
                - - 'arn:aws:s3:::'
                  - Ref: 'MyBucketImage'
                  - '/*'

  MyBucketDocker:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: lks-dockerimage-cana-25
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      VersioningConfiguration:
        Status: Enabled
  MyBucketPolicyDocker:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket:
        Ref: 'MyBucketDocker'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: "s3:GetObject"
            Resource:
              Fn::Join:
                - ''
                - - 'arn:aws:s3:::'
                  - Ref: 'MyBucketDocker'
                  - '/*'


 